kobit_test/config/routes.rb
Rails.application.routes.draw do
  resources :my_likes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

kobit_test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

kobit_test/app/models/my_like.rb
class MyLike < ApplicationRecord
end

kobit_test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

kobit_test/app/controllers/my_likes_controller.rb
class MyLikesController < ApplicationController
  before_action :set_my_like, only: [:show, :edit, :update, :destroy]

  # GET /my_likes
  # GET /my_likes.json
  def index
    @my_likes = MyLike.all
  end

  # GET /my_likes/1
  # GET /my_likes/1.json
  def show
  end

  # GET /my_likes/new
  def new
    @my_like = MyLike.new
  end

  # GET /my_likes/1/edit
  def edit
  end

  # POST /my_likes
  # POST /my_likes.json
  def create
    @my_like = MyLike.new(my_like_params)

    respond_to do |format|
      if @my_like.save
        format.html { redirect_to @my_like, notice: 'My like was successfully created.' }
        format.json { render :show, status: :created, location: @my_like }
      else
        format.html { render :new }
        format.json { render json: @my_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_likes/1
  # PATCH/PUT /my_likes/1.json
  def update
    respond_to do |format|
      if @my_like.update(my_like_params)
        format.html { redirect_to @my_like, notice: 'My like was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_like }
      else
        format.html { render :edit }
        format.json { render json: @my_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_likes/1
  # DELETE /my_likes/1.json
  def destroy
    @my_like.destroy
    respond_to do |format|
      format.html { redirect_to my_likes_url, notice: 'My like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_like
      @my_like = MyLike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_like_params
      params.require(:my_like).permit(:name, :fruit)
    end
end

kobit_test/app/helpers/application_helper.rb
module ApplicationHelper
end

kobit_test/app/helpers/my_likes_helper.rb
module MyLikesHelper
end

kobit_test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KobitTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

kobit_test/app/views/my_likes/_form.html.erb
<%= form_with(model: my_like, local: true) do |form| %>
  <% if my_like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_like.errors.count, "error") %> prohibited this my_like from being saved:</h2>

      <ul>
      <% my_like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :my_like_name %>
  </div>

  <div class="field">
    <%= form.label :fruit %>
    <%= form.text_field :fruit, id: :my_like_fruit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

kobit_test/app/views/my_likes/edit.html.erb
<h1>Editing My Like</h1>

<%= render 'form', my_like: @my_like %>

<%= link_to 'Show', @my_like %> |
<%= link_to 'Back', my_likes_path %>

kobit_test/app/views/my_likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Likes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fruit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_likes.each do |my_like| %>
      <tr>
        <td><%= my_like.name %></td>
        <td><%= my_like.fruit %></td>
        <td><%= link_to 'Show', my_like %></td>
        <td><%= link_to 'Edit', edit_my_like_path(my_like) %></td>
        <td><%= link_to 'Destroy', my_like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Like', new_my_like_path %>

kobit_test/app/views/my_likes/new.html.erb
<h1>New My Like</h1>

<%= render 'form', my_like: @my_like %>

<%= link_to 'Back', my_likes_path %>

kobit_test/app/views/my_likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @my_like.name %>
</p>

<p>
  <strong>Fruit:</strong>
  <%= @my_like.fruit %>
</p>

<%= link_to 'Edit', edit_my_like_path(@my_like) %> |
<%= link_to 'Back', my_likes_path %>